[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Filesystem configuration
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    mobizt/Firebase ESP32 Client @ ^4.4.10
